name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VPS_DOMAIN }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish .NET app
      run: dotnet publish ./rental-services.Server/rental-services.Server.csproj -r linux-x64 --self-contained true --output ./published

    - name: Clear target directory on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
          rm -rf /var/web/*
    
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        source: "published/"
        target: "/var/web"

    - name: Copy and rename native .so files to match expected names
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
            mkdir -p /var/web/published/x64
            cp /usr/lib/x86_64-linux-gnu/liblept.so.5.0.4 /var/web/published/x64/libleptonica-1.82.0.so
            cp /usr/lib/x86_64-linux-gnu/libtesseract.so.5.0.3 /var/web/published/x64/libtesseract50.so

    - name: Copy images to temporary directory
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        source: "images/"
        target: "/tmp"

    - name: Move images to web directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
          rm -rf /var/www/images/*
          cp -a /tmp/images/. /var/www/images/
          rm -rf /tmp/images
          sudo chown -R www-data:www-data /var/www/images
          sudo chmod -R 777 /var/www/images;


    - name: Restart service on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        script: |
          sudo systemctl restart xeonggia.service